server:
  port: 8011


eureka:
    instance:
      hostname: localhost
      # 发呆时间，即服务失效时间（缺省为90s）,就是超过15秒没有续约就会从注册表中剔除
      lease-expiration-duration-in-seconds: 15
      # 心跳时间，即服务续约间隔时间（缺省为30s）
      lease-renewal-interval-in-seconds: 5
    client:
     #设置eureka服务器所在的地址，查询服务和注册服务都需要依赖这个地址。高可用的注册中心时，
      #可以配置多个注册中心，通过逗号隔开
      service-url:
       defaultZone: http://localhost:8010/eureka/
spring:
  application:
     #这在以后的服务与服务之间相互调用一般都是根据这个name
    name: user
  datasource:
    data-password: root
    data-username: root
    url: jdbc:mysql://localhost:3306/reptile?useUnicode=true&amp;characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  type-aliases-package: com.alen.user.model.entity
  mapperLocations: classpath*:mapper/*.xml


