server:
  port: 8010
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: localhost
  client:
    #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    registerWithEureka: false
    #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    fetchRegistry: false
    serviceUrl:
      #设置eureka服务器所在的地址，查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 关闭自我保护模式（缺省为打开）
    enable-self-preservation: false

#应用路径  实际测试时如果设置了server.context-path，
#客户端报com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
